-- MySQL Script generated by MySQL Workbench
-- 11/27/16 16:23:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wikidata
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wikidata` ;

-- -----------------------------------------------------
-- Schema wikidata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wikidata` DEFAULT CHARACTER SET utf8 ;
USE `wikidata` ;

-- -----------------------------------------------------
-- Table `wikidata`.`entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`entity` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`entity` (
  `serial_id` BIGINT(32) NOT NULL,
  `entity_id` VARCHAR(32) NOT NULL,
  `entity_language` VARCHAR(8) NOT NULL,
  `entity_type` VARCHAR(16) NULL DEFAULT NULL,
  `entity_text` VARBINARY(255) NULL DEFAULT NULL,
  PRIMARY KEY (`serial_id`))
ENGINE = InnoDB;

CREATE INDEX `EID` ON `wikidata`.`entity` (`entity_id` ASC);

CREATE INDEX `ELANG` ON `wikidata`.`entity` (`entity_language` ASC);

CREATE INDEX `ETYPE` ON `wikidata`.`entity` (`entity_type` ASC);


-- -----------------------------------------------------
-- Table `wikidata`.`mainsnak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`mainsnak` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`mainsnak` (
  `snak_id` VARCHAR(64) NOT NULL,
  `entity_id` VARCHAR(32) NOT NULL,
  `property_id` VARCHAR(32) NOT NULL,
  `serial` INT(4) NOT NULL,
  `claimtype` VARCHAR(32) NULL DEFAULT NULL,
  `snaktype` VARCHAR(32) NULL DEFAULT NULL,
  `datatype` VARCHAR(32) NULL DEFAULT NULL,
  `rank` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;

CREATE INDEX `EID` ON `wikidata`.`mainsnak` (`entity_id` ASC);

CREATE INDEX `PID` ON `wikidata`.`mainsnak` (`property_id` ASC);

CREATE INDEX `CTYPE` ON `wikidata`.`mainsnak` (`claimtype` ASC);

CREATE INDEX `STYPE` ON `wikidata`.`mainsnak` (`snaktype` ASC);

CREATE INDEX `DTYPE` ON `wikidata`.`mainsnak` (`datatype` ASC);


-- -----------------------------------------------------
-- Table `wikidata`.`description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`description` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`description` (
  `serial_id` BIGINT(32) NOT NULL,
  `entity_id` VARCHAR(32) NOT NULL,
  `desc_language` VARCHAR(8) NULL,
  `desc_text` VARBINARY(255) NULL,
  PRIMARY KEY (`serial_id`))
ENGINE = InnoDB;

CREATE INDEX `EID` ON `wikidata`.`description` (`entity_id` ASC);

CREATE INDEX `DLANG` ON `wikidata`.`description` (`desc_language` ASC);


-- -----------------------------------------------------
-- Table `wikidata`.`datavalue_string`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`datavalue_string` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`datavalue_string` (
  `snak_id` VARCHAR(64) NOT NULL,
  `value` VARBINARY(255) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikidata`.`datavalue_wikibase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`datavalue_wikibase` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`datavalue_wikibase` (
  `snak_id` VARCHAR(64) NOT NULL,
  `id` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikidata`.`datavalue_globecoordinate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`datavalue_globecoordinate` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`datavalue_globecoordinate` (
  `snak_id` VARCHAR(64) NOT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  `altitude` FLOAT NULL DEFAULT NULL,
  `precision` FLOAT NULL DEFAULT NULL,
  `globe` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikidata`.`datavalue_quantity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`datavalue_quantity` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`datavalue_quantity` (
  `snak_id` VARCHAR(64) NOT NULL,
  `amount` VARCHAR(64) NULL DEFAULT NULL,
  `upperBound` VARCHAR(64) NULL DEFAULT NULL,
  `lowerBound` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikidata`.`datavalue_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`datavalue_time` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`datavalue_time` (
  `snak_id` VARCHAR(64) NOT NULL,
  `time` VARCHAR(64) NULL DEFAULT NULL,
  `timezone` VARCHAR(32) NULL DEFAULT NULL,
  `before` VARCHAR(32) NULL DEFAULT NULL,
  `after` VARCHAR(32) NULL DEFAULT NULL,
  `precision` INT(8) NULL DEFAULT NULL,
  `calendarmodel` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`snak_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wikidata`.`qualifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wikidata`.`qualifier` ;

CREATE TABLE IF NOT EXISTS `wikidata`.`qualifier` (
  `hash` VARCHAR(64) NOT NULL,
  `snaktype` VARCHAR(32) NULL,
  `property_id` VARCHAR(32) NULL,
  `datatype` VARCHAR(32) NULL,
  PRIMARY KEY (`hash`))
ENGINE = InnoDB;

CREATE INDEX `STYPE` ON `wikidata`.`qualifier` (`snaktype` ASC);

CREATE INDEX `PID` ON `wikidata`.`qualifier` (`property_id` ASC);

CREATE INDEX `DTYPE` ON `wikidata`.`qualifier` (`datatype` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
